# Generated by Django 3.2.6 on 2021-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
