# Generated by Django 3.2.6 on 2021-10-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
