# Generated by Django 3.2.6 on 2021-10-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
    ]
